minecat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings

from . import views


urlpatterns = [
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name='index'),

]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG is True:

    import debug_toolbar

    urlpatterns += [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.list_minerals, name='list'),
    url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'first_letter/(?P<alpha>\w)', views.minerals_by_first_letter, name='minerals_by_first_letter'),
    url(r'group/(?P<group>\w+\s*)', views.minerals_by_group, name='minerals_by_group'),
    url(r'search/$', views.search, name='search'),
]

minerals/models.py
from django.db import models

import json


class Mineral(models.Model):
    name = models.CharField(max_length=255, null=True)
    image_filename = models.CharField(max_length=255, null=True)
    image_caption = models.CharField(max_length=255, null=True)
    category = models.CharField(max_length=255, null=True)
    formula = models.CharField(max_length=255, null=True)
    strunz_classification = models.CharField(max_length=255, null=True)
    crystal_system = models.CharField(max_length=255, null=True)
    unit_cell = models.CharField(max_length=255, null=True)
    color = models.CharField(max_length=255, null=True)
    crystal_symmetry = models.CharField(max_length=255, null=True)
    cleavage = models.CharField(max_length=255, null=True)
    mohs_scale_hardness = models.CharField(max_length=255, null=True)
    luster = models.CharField(max_length=255, null=True)
    streak = models.CharField(max_length=255, null=True)
    diaphaneity = models.CharField(max_length=255, null=True)
    optical_properties = models.CharField(max_length=255, null=True)
    refractive_index = models.CharField(max_length=255, null=True)
    crystal_habit = models.CharField(max_length=255, null=True)
    specific_gravity = models.CharField(max_length=255, null=True)
    group = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name

    def get_all_fields(self):
        """Returns a list of all field names on the instance."""
        fields = []
        excluded_fields = ('id', 'status', 'workshop', 'user', 'complete', 'name', 'image',
                           'image_filename', 'image_caption')
        for f in self._meta.fields:

            fname = f.name
            # resolve picklists/choices, with get_xyz_display() function
            get_choice = 'get_' + fname + '_display'
            if hasattr(self, get_choice):
                value = getattr(self, get_choice)()
            else:
                try:
                    value = getattr(self, fname)
                except AttributeError:
                    value = None

            # only display fields with values and skip some fields entirely
            if f.editable and value and f.name not in excluded_fields:
                fields.append(
                    {
                        'label': f.verbose_name.title(),
                        'name': f.name,
                        'value': value,
                    }
                )
        return fields



def JSONReader(filename):
    with open(filename) as data_file:
        data = json.load(data_file)
    return clean(data)


def clean(data):
    cdat = []
    for d in data:
        cd = {}
        for k,v in d.items():
                new_k = k.replace(" ", '_')
                if new_k == 'image_filename':
                    cd['image_filename'] = 'images/{}.jpg'.format(d['name'])
                else:
                    cd[new_k] = v

        cdat.append(cd)
    return cdat


def save_images():
    minerals = Mineral.objects.all()
    for m in minerals:
        m.image = m.image_filename
        m.save()


def initialize():
    try:
        minerals = JSONReader('minerals/static/data/minerals.json')
        for mineral in minerals:
            Mineral.objects.create(**mineral)
    except ValueError:
        pass

minecat/views.py
from django.shortcuts import render

from minerals import models


def home(request):
    minerals = models.Mineral.objects.all()

    return render(request, 'minerals/index.html', {'minerals': minerals})

minerals/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count, Sum

from .models import Mineral


def list_minerals(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/index.html', {'minerals': minerals})


def detail(request, pk):
    mineral = get_object_or_404(Mineral, pk=pk)
    return render(request, 'minerals/detail.html', {'mineral': mineral})


def minerals_by_first_letter(request, alpha):
    minerals = Mineral.objects.filter(name__startswith=alpha.lower())
    return render(request, 'minerals/index.html', {'minerals': minerals, 'current': alpha})


def minerals_by_group(request, group):
    g = group.lower()
    minerals = Mineral.objects.filter(group__icontains=g)
    return render(request, 'minerals/index.html', {'minerals': minerals, 'current': g})


def search(request):
    term = request.GET['q']
    minerals = Mineral.objects.filter(Q(name__icontains=term)|Q(image_caption__icontains=term))
    return render(request, 'minerals/index.html', {'minerals': minerals})

minerals/templates/minerals/detail.html
{% extends 'minerals/layout.html' %}

{% block title %}{{ mineral.name }}{% endblock %}

{% load static %}

{% load mineral_extras %}

{% block content %}


  <div class="bounds bounds--small">
{% logo_header %}
    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ mineral.name }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static mineral.image_filename %}">
        <p class="mineral__caption">{{ mineral.image_caption }}</p  >
      </div>

      <div class="mineral__table-container">
        <table class="mineral__table">
        {% for field in mineral.get_all_fields %}
            {% if field.name == 'category' %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value  }}</td>
                </tr>
            {% elif field.name == 'formula' %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value | markdown_to_html | safe }}</td>
                </tr>
            {% else %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </table>
      </div>
    </div>
  </div>

{% endblock %}

minerals/templates/minerals/index.html
{% extends 'minerals/layout.html' %}
{% load mineral_extras %}
{%  load static %}
{% block title %}Minerals{% endblock %}
{% block content %}
  <div class="bounds">
    {%  logo_header %}
    <div class="grid-100">
      <ul class="minerals__container">
          {% for mineral in minerals %}
            <li class="minerals__item">
              <a class="minerals__anchor" href="{%  url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
            </li>
          {% endfor %}
      </ul>
    </div>
  </div>


{% endblock %}

minerals/templates/minerals/layout.html
{% load static %}
{% load mineral_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MineCat: {% block title %}{% endblock %} </title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "css/global.css" %}">
</head>
<body>

    {% block content %}

     {% endblock %}

{% random_mineral %}
</body>
</html>

minerals/templates/minerals/logo_header.html
  <div class="grid-100">
      <a href="{% url "minerals:list" %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
  </div>

templates/layout.html
<!DOCTYPE html>

{% load static %}
{% load mineral_extras %}


<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MineCat: {% block title %}{% endblock %} </title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "css/global.css" %}">
</head>
<body>

    <div class="bounds">
        {% logo_header %}
        <nav class="text-centered">
            <form class='form' action="{% url 'minerals:search' %}" method="GET">
                <input type="search" name="q">
                <button type="submit" class="">Search</button>
            </form>
        </nav>
        {% alpha_nav current %}
    <br>
        {% group_search current %}
        {% block content %}
        {% endblock %}
    </div>

    {% random_mineral %}

</body>
</html>

templates/minerals/alpha_nav.html
<nav class="text-centered">

        {% for a in alpha_list %}
            <a href="{% url 'minerals:minerals_by_first_letter' alpha=a%}" class="{% if current == a %}active{% endif %}">{{ a }}</a>
        {% endfor %}

</nav>

templates/minerals/detail.html
{% extends 'layout.html' %}

{% block title %}{{ mineral.name }}{% endblock %}

{% load static %}

{% load mineral_extras %}

{% block content %}


  <div class="bounds bounds--small">
    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ mineral.name }}</h1>
      <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static mineral.image_filename %}">
        <p class="mineral__caption">{{ mineral.image_caption }}</p  >
      </div>

      <div class="mineral__table-container">
        <table class="mineral__table">
        {% for field in mineral.get_all_fields %}
            {% if field.name == 'category' %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value  }}</td>
                </tr>
            {% elif field.name == 'formula' %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value | markdown_to_html | safe }}</td>
                </tr>
            {% else %}
                <tr>
                    <td class="mineral__category">{{ field.label }}</td>
                    <td class="mineral__category">{{ field.value }}</td>
                </tr>
            {% endif %}
        {% endfor %}
        </table>
      </div>
    </div>
  </div>

{% endblock %}

templates/minerals/group_nav.html
<nav class="text-centered">
|
    {% for g in groups %}

            <a href="{% url 'minerals:minerals_by_group' group=g %}" class="mineral__group {% if current == g %}active{% endif %}">{{ g }}</a> |

    {% endfor %}
</nav>

templates/minerals/index.html
{% extends 'layout.html' %}
{% load mineral_extras %}
{%  load static %}
{% block title %}Minerals{% endblock %}
{% block content %}

    <div class="grid-100">
        <ul class="minerals__container">
          {% for mineral in minerals %}
            <li class="minerals__item">
              <a class="minerals__anchor" href="{%  url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
            </li>
          {% endfor %}
      </ul>
    </div>

{% endblock %}

templates/minerals/logo_header.html
  <div class="grid-100">
      <a href="{% url "minerals:list" %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Greg's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>

  </div>

templates/minerals/random_mineral.html
<div class="minerals__random">
    <a class="minerals__anchor" href="{% url "minerals:detail" pk=mineral.pk %}">Show random mineral</a>
</div>